// pkg/runner/server/ui/frontend/src/components/ActionCatalog.tsx
import { useMemo, useState } from "react";
import type { ActionSpec } from "../types/workflow";
import { filterActionCatalog } from "../utils/actionCatalog";
import { filterControlNodes, type ControlNodeType } from "../utils/graphEditing";

interface ActionCatalogProps {
  actions: ActionSpec[];
  onAddAction: (action: string) => void;
  onAddControlNode: (type: ControlNodeType) => void;
}

export default function ActionCatalog({ actions, onAddAction, onAddControlNode }: ActionCatalogProps) {
  const [query, setQuery] = useState("");
  const groups = useMemo(() => filterActionCatalog(actions, query), [actions, query]);
  const controlNodes = useMemo(() => filterControlNodes(query), [query]);
  const visibleCount = groups.reduce((total, group) => total + group.actions.length, 0) + controlNodes.length;

  return (
    <aside className="library-panel">
      <div className="panel-heading">
        <span>Actions</span>
        <small>
          {visibleCount} / {actions.length}
        </small>
      </div>

      <label className="catalog-search">
        <span>⌕</span>
        <input value={query} type="search" placeholder="Search actions" onChange={(event) => setQuery(event.target.value)} />
      </label>

      {controlNodes.length || groups.length ? (
        <div className="catalog-groups">
          {controlNodes.length ? (
            <section className="catalog-group">
              <div className="catalog-group-heading">
                <span>Graph controls</span>
                <small>{controlNodes.length}</small>
              </div>
              {controlNodes.map((control) => (
                <button
                  key={control.type}
                  className="action-card control-card"
                  draggable
                  type="button"
                  onClick={() => onAddControlNode(control.type)}
                  onDragStart={(event) => handleControlDragStart(event, control.type)}
                >
                  <span className="action-card-title">
                    <strong>{control.title}</strong>
                    <small className="risk-badge risk-read_only">{control.type}</small>
                  </span>
                  <span className="action-description">{control.description}</span>
                </button>
              ))}
            </section>
          ) : null}

          {groups.map((group) => (
            <section key={group.category} className="catalog-group">
              <div className="catalog-group-heading">
                <span>{group.category}</span>
                <small>{group.actions.length}</small>
              </div>
              {group.actions.map((action) => (
                <button
                  key={action.action}
                  className="action-card"
                  draggable
                  type="button"
                  onClick={() => onAddAction(action.action)}
                  onDragStart={(event) => handleDragStart(event, action)}
                >
                  <span className="action-card-title">
                    <strong>{action.title}</strong>
                    <small className={`risk-badge ${riskClass(action)}`}>{riskLabel(action)}</small>
                  </span>
                  <small>{action.action}</small>
                  {action.description ? <span className="action-description">{action.description}</span> : null}
                  <span className="action-flags">
                    {action.experimental ? <small>experimental</small> : null}
                    {action.deprecated ? <small>deprecated</small> : null}
                    {action.required_args?.length ? <small>requires {action.required_args.join(", ")}</small> : null}
                  </span>
                </button>
              ))}
            </section>
          ))}
        </div>
      ) : (
        <div className="empty-state">No actions match this search.</div>
      )}
    </aside>
  );
}

function riskClass(action: ActionSpec) {
  return `risk-${(action.risk || "medium").replace(/[^a-z0-9_-]/gi, "_")}`;
}

function riskLabel(action: ActionSpec) {
  return action.risk || "medium";
}

function handleDragStart(event: React.DragEvent, action: ActionSpec) {
  event.dataTransfer.setData("application/runner-action", action.action);
  event.dataTransfer.setData("text/plain", action.action);
  event.dataTransfer.effectAllowed = "copy";
}

function handleControlDragStart(event: React.DragEvent, type: ControlNodeType) {
  event.dataTransfer.setData("application/runner-node-type", type);
  event.dataTransfer.setData("text/plain", type);
  event.dataTransfer.effectAllowed = "copy";
}

// pkg/runner/server/ui/frontend/src/components/ActionCatalog.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import { Search } from "lucide-vue-next";
import type { ActionSpec } from "../types/workflow";
import { filterActionCatalog } from "../utils/actionCatalog";
import { filterControlNodes, type ControlNodeType } from "../utils/graphEditing";

const props = defineProps<{
  actions: ActionSpec[];
}>();

const emit = defineEmits<{
  "add-action": [action: string];
  "add-control-node": [type: ControlNodeType];
}>();

const query = ref("");
const groups = computed(() => filterActionCatalog(props.actions, query.value));
const controlNodes = computed(() => filterControlNodes(query.value));
const visibleCount = computed(() => groups.value.reduce((total, group) => total + group.actions.length, 0) + controlNodes.value.length);

function riskClass(action: ActionSpec) {
  return `risk-${(action.risk || "medium").replace(/[^a-z0-9_-]/gi, "_")}`;
}

function riskLabel(action: ActionSpec) {
  return action.risk || "medium";
}

function handleDragStart(event: DragEvent, action: ActionSpec) {
  event.dataTransfer?.setData("application/runner-action", action.action);
  event.dataTransfer?.setData("text/plain", action.action);
  if (event.dataTransfer) {
    event.dataTransfer.effectAllowed = "copy";
  }
}

function handleControlDragStart(event: DragEvent, type: ControlNodeType) {
  event.dataTransfer?.setData("application/runner-node-type", type);
  event.dataTransfer?.setData("text/plain", type);
  if (event.dataTransfer) {
    event.dataTransfer.effectAllowed = "copy";
  }
}
</script>

<template>
  <aside class="library-panel">
    <div class="panel-heading">
      <span>Actions</span>
      <small>{{ visibleCount }} / {{ actions.length }}</small>
    </div>

    <label class="catalog-search">
      <Search :size="15" />
      <input v-model="query" type="search" placeholder="Search actions" />
    </label>

    <div v-if="controlNodes.length || groups.length" class="catalog-groups">
      <section v-if="controlNodes.length" class="catalog-group">
        <div class="catalog-group-heading">
          <span>Graph controls</span>
          <small>{{ controlNodes.length }}</small>
        </div>
        <button
          v-for="control in controlNodes"
          :key="control.type"
          class="action-card control-card"
          draggable="true"
          type="button"
          @click="emit('add-control-node', control.type)"
          @dragstart="handleControlDragStart($event, control.type)"
        >
          <span class="action-card-title">
            <strong>{{ control.title }}</strong>
            <small class="risk-badge risk-read_only">{{ control.type }}</small>
          </span>
          <span class="action-description">{{ control.description }}</span>
        </button>
      </section>

      <section v-for="group in groups" :key="group.category" class="catalog-group">
        <div class="catalog-group-heading">
          <span>{{ group.category }}</span>
          <small>{{ group.actions.length }}</small>
        </div>
        <button
          v-for="action in group.actions"
          :key="action.action"
          class="action-card"
          draggable="true"
          type="button"
          @click="emit('add-action', action.action)"
          @dragstart="handleDragStart($event, action)"
        >
          <span class="action-card-title">
            <strong>{{ action.title }}</strong>
            <small :class="['risk-badge', riskClass(action)]">{{ riskLabel(action) }}</small>
          </span>
          <small>{{ action.action }}</small>
          <span v-if="action.description" class="action-description">{{ action.description }}</span>
          <span class="action-flags">
            <small v-if="action.experimental">experimental</small>
            <small v-if="action.deprecated">deprecated</small>
            <small v-if="action.required_args?.length">requires {{ action.required_args.join(", ") }}</small>
          </span>
        </button>
      </section>
    </div>

    <div v-else class="empty-state">No actions match this search.</div>
  </aside>
</template>
