// pkg/runner/server/ui/frontend/src/components/YamlPreviewModal.vue
<script setup lang="ts">
import { computed, ref, watch } from "vue";
import { NAlert, NButton, NModal, NSpace, NTabPane, NTabs, NTag } from "naive-ui";
import CodeEditor from "./CodeEditor.vue";
import type { WorkflowGraph } from "../types/workflow";
import { buildGraphDiffSummary } from "../utils/graphDiff";
import { formatGraphJSON, graphPreviewText } from "../utils/graphPreview";

const props = defineProps<{
  show: boolean;
  graph: WorkflowGraph | null;
  baselineGraph?: WorkflowGraph | null;
  yamlPreview: string;
  previewCompiling?: boolean;
}>();

const emit = defineEmits<{
  "update:show": [show: boolean];
  "replace-graph": [graph: WorkflowGraph];
  "compile-yaml": [];
  "parse-yaml": [yaml: string];
}>();

const activeTab = ref("preview");
const yamlEdit = ref("");
const yamlEditError = ref<string | null>(null);
const graphJSON = ref(formatGraphJSON(props.graph));
const graphJSONError = ref<string | null>(null);

const previewText = computed(() => graphPreviewText(props.graph, props.yamlPreview));
const previewLanguage = computed(() => (props.yamlPreview.trim() ? "yaml" : "yaml"));
const previewLabel = computed(() => (props.yamlPreview.trim() ? "Compiled YAML" : "Graph YAML-like"));
const diffSummary = computed(() => buildGraphDiffSummary(props.baselineGraph, props.graph));

watch(
  () => props.show,
  (show) => {
    if (!show) return;
    activeTab.value = "preview";
    refreshYamlEdit();
    refreshGraphJSON();
  },
);

watch(
  () => [props.graph, props.yamlPreview] as const,
  () => {
    if (activeTab.value !== "yaml") refreshYamlEdit();
    if (activeTab.value !== "graph-json") refreshGraphJSON();
  },
  { deep: true },
);

function close() {
  emit("update:show", false);
}

function refreshGraphJSON() {
  graphJSON.value = formatGraphJSON(props.graph);
  graphJSONError.value = null;
}

function refreshYamlEdit() {
  yamlEdit.value = props.yamlPreview.trim() ? props.yamlPreview : "";
  yamlEditError.value = null;
}

function updateYamlEdit(value: string) {
  yamlEdit.value = value;
  yamlEditError.value = null;
}

function applyYamlEdit() {
  const yaml = yamlEdit.value.trim();
  if (!yaml) {
    yamlEditError.value = "Compile the graph first, or paste workflow YAML.";
    return;
  }
  emit("parse-yaml", yaml);
  yamlEditError.value = null;
}

function updateGraphJSON(value: string) {
  graphJSON.value = value;
  graphJSONError.value = null;
}

function applyGraphJSON() {
  try {
    const parsed = JSON.parse(graphJSON.value) as WorkflowGraph;
    if (!parsed || typeof parsed !== "object" || !Array.isArray(parsed.nodes) || !Array.isArray(parsed.edges)) {
      throw new Error("Graph JSON must include nodes[] and edges[].");
    }
    emit("replace-graph", parsed);
    graphJSONError.value = null;
  } catch (error) {
    graphJSONError.value = error instanceof Error ? error.message : "Invalid graph JSON.";
  }
}
</script>

<template>
  <NModal
    :show="show"
    preset="card"
    class="yaml-preview-modal"
    title="Workflow YAML"
    :bordered="false"
    @update:show="emit('update:show', $event)"
  >
    <NTabs v-model:value="activeTab" type="line" animated>
      <NTabPane name="preview" tab="Preview">
        <div class="modal-tab-heading">
          <NTag size="small" :bordered="false">{{ previewLabel }}</NTag>
          <small v-if="previewCompiling">Compiling latest graph...</small>
          <small v-else-if="!yamlPreview.trim()">Editing graph; compiled YAML will refresh automatically when API is available.</small>
        </div>
        <CodeEditor :model-value="previewText" :language="previewLanguage" readonly height="520px" />
      </NTabPane>

      <NTabPane name="yaml" tab="YAML">
        <div class="modal-tab-heading">
          <NTag size="small" :bordered="false">Editable workflow YAML</NTag>
          <small>Applies through the server YAML parser into the current graph store.</small>
        </div>
        <CodeEditor
          :model-value="yamlEdit"
          language="yaml"
          height="520px"
          placeholder="version: v0.1&#10;name: workflow&#10;steps: []"
          @update:model-value="updateYamlEdit"
        />
        <NAlert v-if="yamlEditError" class="editor-alert" type="error" :bordered="false">
          {{ yamlEditError }}
        </NAlert>
        <NSpace justify="end" class="modal-actions">
          <NButton secondary @click="emit('compile-yaml')">Compile latest graph</NButton>
          <NButton secondary @click="refreshYamlEdit">Reset</NButton>
          <NButton type="primary" @click="applyYamlEdit">Apply YAML to graph</NButton>
        </NSpace>
      </NTabPane>

      <NTabPane name="diff" tab="Diff">
        <div class="modal-tab-heading">
          <NTag size="small" :bordered="false">Change review</NTag>
          <small>{{ diffSummary.changed ? "Review changes before save, dry-run, or run." : "No graph changes from the loaded baseline." }}</small>
        </div>
        <div class="diff-section-grid">
          <section
            v-for="section in diffSummary.sections"
            :key="section.kind"
            class="diff-section-card"
            :class="{ 'diff-section-card--changed': section.changed }"
          >
            <div class="diff-section-heading">
              <strong>{{ section.title }}</strong>
              <NTag size="small" :type="section.changed ? 'warning' : 'success'" :bordered="false">
                {{ section.changed ? "Changed" : "Clean" }}
              </NTag>
            </div>
            <ul v-if="section.paths.length" class="diff-path-list">
              <li v-for="path in section.paths.slice(0, 16)" :key="path">
                <code>{{ path }}</code>
              </li>
            </ul>
            <p v-else class="diff-empty">No changes in this category.</p>
          </section>
        </div>
      </NTabPane>

      <NTabPane name="graph-json" tab="Graph JSON">
        <div class="modal-tab-heading">
          <NTag size="small" :bordered="false">Advanced editor</NTag>
          <small>Applies directly to the current graph store.</small>
        </div>
        <CodeEditor
          :model-value="graphJSON"
          language="json"
          height="520px"
          placeholder="{ &quot;version&quot;: &quot;v1&quot;, &quot;nodes&quot;: [], &quot;edges&quot;: [] }"
          @update:model-value="updateGraphJSON"
        />
        <NAlert v-if="graphJSONError" class="editor-alert" type="error" :bordered="false">
          {{ graphJSONError }}
        </NAlert>
        <NSpace justify="end" class="modal-actions">
          <NButton secondary @click="refreshGraphJSON">Reset</NButton>
          <NButton type="primary" @click="applyGraphJSON">Apply graph JSON</NButton>
        </NSpace>
      </NTabPane>
    </NTabs>

    <template #footer>
      <NSpace justify="end">
        <NButton @click="close">Close</NButton>
      </NSpace>
    </template>
  </NModal>
</template>

// pkg/runner/server/ui/frontend/src/components/YamlPreviewModal.tsx
import { useEffect, useMemo, useState } from "react";
import CodeEditor from "./CodeEditor";
import type { WorkflowGraph } from "../types/workflow";
import { buildGraphDiffSummary } from "../utils/graphDiff";
import { formatGraphJSON, graphPreviewText } from "../utils/graphPreview";

interface YamlPreviewModalProps {
  show: boolean;
  graph: WorkflowGraph | null;
  baselineGraph?: WorkflowGraph | null;
  yamlPreview: string;
  previewCompiling?: boolean;
  onClose: () => void;
  onReplaceGraph: (graph: WorkflowGraph) => void;
  onCompileYaml: () => void;
  onParseYaml: (yaml: string) => void;
}

export default function YamlPreviewModal(props: YamlPreviewModalProps) {
  const [activeTab, setActiveTab] = useState("preview");
  const [yamlEdit, setYamlEdit] = useState("");
  const [yamlEditError, setYamlEditError] = useState<string | null>(null);
  const [graphJSON, setGraphJSON] = useState(formatGraphJSON(props.graph));
  const [graphJSONError, setGraphJSONError] = useState<string | null>(null);
  const previewText = useMemo(() => graphPreviewText(props.graph, props.yamlPreview), [props.graph, props.yamlPreview]);
  const diffSummary = useMemo(() => buildGraphDiffSummary(props.baselineGraph, props.graph), [props.baselineGraph, props.graph]);

  useEffect(() => {
    if (!props.show) return;
    setActiveTab("preview");
    setYamlEdit(props.yamlPreview.trim() ? props.yamlPreview : "");
    setGraphJSON(formatGraphJSON(props.graph));
    setYamlEditError(null);
    setGraphJSONError(null);
  }, [props.show, props.graph, props.yamlPreview]);

  if (!props.show) return null;

  function applyYamlEdit() {
    const yaml = yamlEdit.trim();
    if (!yaml) {
      setYamlEditError("Compile the graph first, or paste workflow YAML.");
      return;
    }
    props.onParseYaml(yaml);
    setYamlEditError(null);
  }

  function applyGraphJSON() {
    try {
      const parsed = JSON.parse(graphJSON) as WorkflowGraph;
      if (!parsed || typeof parsed !== "object" || !Array.isArray(parsed.nodes) || !Array.isArray(parsed.edges)) {
        throw new Error("Graph JSON must include nodes[] and edges[].");
      }
      props.onReplaceGraph(parsed);
      setGraphJSONError(null);
    } catch (error) {
      setGraphJSONError(error instanceof Error ? error.message : "Invalid graph JSON.");
    }
  }

  return (
    <div className="modal-backdrop">
      <section className="yaml-preview-modal modal-card">
        <div className="modal-header"><h2>Workflow YAML</h2><button type="button" onClick={props.onClose}>×</button></div>
        <TabButtons active={activeTab} tabs={["preview", "yaml", "diff", "graph-json"]} onChange={setActiveTab} />
        {activeTab === "preview" ? <><div className="modal-tab-heading"><span className="tag">{props.yamlPreview.trim() ? "Compiled YAML" : "Graph YAML-like"}</span><small>{props.previewCompiling ? "Compiling latest graph..." : "Editing graph; compiled YAML refreshes when API is available."}</small></div><CodeEditor value={previewText} language="yaml" readonly height="520px" /></> : null}
        {activeTab === "yaml" ? <><div className="modal-tab-heading"><span className="tag">Editable workflow YAML</span><small>Applies through the server YAML parser into the current graph store.</small></div><CodeEditor value={yamlEdit} language="yaml" height="520px" onChange={(value) => { setYamlEdit(value); setYamlEditError(null); }} />{yamlEditError ? <div className="inline-alert is-error">{yamlEditError}</div> : null}<div className="modal-actions"><button type="button" onClick={props.onCompileYaml}>Compile latest graph</button><button type="button" onClick={() => setYamlEdit(props.yamlPreview.trim() ? props.yamlPreview : "")}>Reset</button><button type="button" onClick={applyYamlEdit}>Apply YAML to graph</button></div></> : null}
        {activeTab === "diff" ? <div className="diff-section-grid">{diffSummary.sections.map((section) => <section key={section.kind} className={`diff-section-card ${section.changed ? "diff-section-card--changed" : ""}`}><div className="diff-section-heading"><strong>{section.title}</strong><span className={`tag ${section.changed ? "tag-warning" : "tag-success"}`}>{section.changed ? "Changed" : "Clean"}</span></div>{section.paths.length ? <ul className="diff-path-list">{section.paths.slice(0, 16).map((path) => <li key={path}><code>{path}</code></li>)}</ul> : <p className="diff-empty">No changes in this category.</p>}</section>)}</div> : null}
        {activeTab === "graph-json" ? <><div className="modal-tab-heading"><span className="tag">Advanced editor</span><small>Applies directly to the current graph store.</small></div><CodeEditor value={graphJSON} language="json" height="520px" onChange={(value) => { setGraphJSON(value); setGraphJSONError(null); }} />{graphJSONError ? <div className="inline-alert is-error">{graphJSONError}</div> : null}<div className="modal-actions"><button type="button" onClick={() => setGraphJSON(formatGraphJSON(props.graph))}>Reset</button><button type="button" onClick={applyGraphJSON}>Apply graph JSON</button></div></> : null}
        <div className="modal-actions"><button type="button" onClick={props.onClose}>Close</button></div>
      </section>
    </div>
  );
}

function TabButtons({ active, tabs, onChange }: { active: string; tabs: string[]; onChange: (tab: string) => void }) {
  return <div className="tab-buttons">{tabs.map((tab) => <button key={tab} type="button" className={active === tab ? "is-active" : ""} onClick={() => onChange(tab)}>{tab}</button>)}</div>;
}
