// web/src/pages/ApprovalManagementPage.vue
<script setup>
import { computed, h, onMounted, reactive, ref, watch } from "vue";
import { useRouter } from "vue-router";
import { useAppStore } from "../store";
import { NTag, NButton, NSwitch } from "naive-ui";
import {
  ArrowLeftIcon,
  CheckCircleIcon,
  ClockIcon,
  FilterIcon,
  RefreshCcwIcon,
  ShieldCheckIcon,
  TerminalIcon,
  XCircleIcon,
} from "lucide-vue-next";
import {
  disableApprovalGrant,
  enableApprovalGrant,
  fetchApprovalAudits,
  fetchApprovalGrants,
  revokeApprovalGrant,
} from "../api/approvalManagement";

const router = useRouter();
const store = useAppStore();

const activeTab = ref("audits");
const stats = reactive({ todayTotal: 0, pending: 0, autoAccepted: 0, grantedCommands: 0 });
const filters = reactive({ timeRange: null, sessionKind: "", host: "", operator: "", decision: "", toolName: "" });
const audits = ref([]);
const auditPage = ref(1);
const auditPageSize = ref(20);
const auditTotal = ref(0);
const auditLoading = ref(false);
const auditTotalPages = computed(() => Math.max(1, Math.ceil(auditTotal.value / auditPageSize.value)));
const drawerVisible = ref(false);
const drawerRecord = ref(null);
const grants = ref([]);
const grantsLoading = ref(false);
const grantsHostId = ref("");

function buildAuditQuery() {
  const params = new URLSearchParams();
  params.set("page", String(auditPage.value));
  params.set("pageSize", String(auditPageSize.value));
  if (filters.timeRange) params.set("timeRange", filters.timeRange);
  if (filters.sessionKind) params.set("sessionKind", filters.sessionKind);
  if (filters.host) params.set("host", filters.host);
  if (filters.operator) params.set("operator", filters.operator);
  if (filters.decision) params.set("decision", filters.decision);
  if (filters.toolName) params.set("toolName", filters.toolName);
  return params.toString();
}

async function fetchAudits() {
  auditLoading.value = true;
  try {
    const query = buildAuditQuery();
    const data = await fetchApprovalAudits(Object.fromEntries(new URLSearchParams(query).entries()));
    audits.value = data.items || [];
    auditTotal.value = data.total || 0;
    stats.todayTotal = data.stats?.todayTotal ?? stats.todayTotal;
    stats.pending = data.stats?.pending ?? stats.pending;
    stats.autoAccepted = data.stats?.autoAccepted ?? stats.autoAccepted;
    stats.grantedCommands = data.stats?.grantedCommands ?? stats.grantedCommands;
  } catch (err) { console.error("[ApprovalManagement] fetchAudits failed:", err); }
  finally { auditLoading.value = false; }
}

async function fetchGrants(hostId) {
  grantsLoading.value = true;
  try {
    const data = await fetchApprovalGrants(hostId);
    grants.value = data.items || [];
  } catch (err) { console.error("[ApprovalManagement] fetchGrants failed:", err); }
  finally { grantsLoading.value = false; }
}

async function grantAction(grantId, action) {
  try {
    if (action === "revoke") await revokeApprovalGrant(grantId);
    else if (action === "disable") await disableApprovalGrant(grantId);
    else if (action === "enable") await enableApprovalGrant(grantId);
    await fetchGrants(grantsHostId.value);
  } catch (err) { console.error(`[ApprovalManagement] grantAction(${action}) failed:`, err); }
}

function revokeGrant(grantId) { return grantAction(grantId, "revoke"); }
function disableGrant(grantId) { return grantAction(grantId, "disable"); }
function enableGrant(grantId) { return grantAction(grantId, "enable"); }

function applyFilters() { auditPage.value = 1; fetchAudits(); }
function resetFilters() {
  Object.assign(filters, { timeRange: null, sessionKind: "", host: "", operator: "", decision: "", toolName: "" });
  applyFilters();
}

function decisionTagType(decision) {
  switch (decision) {
    case "approved": return "success";
    case "rejected": return "error";
    case "auto_accepted": return "info";
    case "pending": return "warning";
    default: return "default";
  }
}
function decisionLabel(decision) {
  switch (decision) {
    case "approved": return "已批准";
    case "rejected": return "已拒绝";
    case "auto_accepted": return "自动放行";
    case "pending": return "待审核";
    default: return decision || "未知";
  }
}
function grantStatusType(status) {
  switch (status) {
    case "active": return "success";
    case "disabled": return "warning";
    case "revoked": return "error";
    default: return "default";
  }
}
function grantStatusLabel(status) {
  switch (status) {
    case "active": return "生效中";
    case "disabled": return "已禁用";
    case "revoked": return "已撤销";
    default: return status || "未知";
  }
}
function formatTime(value) {
  if (!value) return "-";
  const d = new Date(value);
  if (Number.isNaN(d.getTime())) return value;
  return d.toLocaleString("zh-CN", { hour12: false });
}

function openDrawer(record) { drawerRecord.value = record; drawerVisible.value = true; }
function closeDrawer() { drawerVisible.value = false; drawerRecord.value = null; }

// Audit table columns
const auditColumns = [
  { title: "时间", key: "createdAt", render: (row) => formatTime(row.createdAt) },
  { title: "会话类型", key: "sessionKind", render: (row) => row.sessionKind || "-" },
  { title: "主机", key: "host", render: (row) => row.host || "-" },
  { title: "操作人", key: "operator", render: (row) => row.operator || "-" },
  { title: "工具", key: "toolName", render: (row) => row.toolName || "-" },
  {
    title: "决策",
    key: "decision",
    render: (row) => h(NTag, { type: decisionTagType(row.decision), size: "small" }, { default: () => decisionLabel(row.decision) }),
  },
  {
    title: "操作",
    key: "actions",
    render: (row) => h(NButton, { size: "small", quaternary: true, onClick: () => openDrawer(row) }, { default: () => "详情" }),
  },
];

// Grants table columns
const grantColumns = [
  { title: "授权 ID", key: "id" },
  { title: "主机", key: "hostId", render: (row) => row.hostId || "-" },
  { title: "命令/工具", key: "command", render: (row) => row.command || row.toolName || "-" },
  { title: "授权时间", key: "grantedAt", render: (row) => formatTime(row.grantedAt) },
  {
    title: "状态",
    key: "status",
    render: (row) => h(NTag, { type: grantStatusType(row.status), size: "small" }, { default: () => grantStatusLabel(row.status) }),
  },
  {
    title: "操作",
    key: "actions",
    render: (row) => {
      const buttons = [];
      if (row.status === "active") {
        buttons.push(h(NButton, { size: "small", quaternary: true, onClick: () => revokeGrant(row.id) }, { default: () => "撤销" }));
        buttons.push(h(NButton, { size: "small", quaternary: true, onClick: () => disableGrant(row.id) }, { default: () => "禁用" }));
      }
      if (row.status === "disabled") {
        buttons.push(h(NButton, { size: "small", type: "primary", quaternary: true, onClick: () => enableGrant(row.id) }, { default: () => "启用" }));
      }
      return h("div", { style: "display:flex;gap:6px" }, buttons);
    },
  },
];

watch(activeTab, (tab) => { if (tab === "grants") fetchGrants(grantsHostId.value); });
watch(grantsHostId, (hostId) => { if (activeTab.value === "grants") fetchGrants(hostId); });
onMounted(() => { fetchAudits(); });
</script>

<template>
  <div class="approval-page" data-testid="approval-management-page">
    <header class="approval-header">
      <n-button text @click="router.push('/')"><ArrowLeftIcon :size="16" /> 返回工作区</n-button>
      <div class="header-copy">
        <h1>审批管理</h1>
        <p>集中查看审批流水、授权记录，管理命令授权的生命周期。</p>
      </div>
    </header>

    <n-grid :cols="4" :x-gap="12" :y-gap="12" responsive="screen" :item-responsive="true" data-testid="stats-row">
      <n-gi span="4 m:1">
        <n-card size="small"><n-statistic label="今日审批" :value="stats.todayTotal" data-testid="stat-today-total" /></n-card>
      </n-gi>
      <n-gi span="4 m:1">
        <n-card size="small"><n-statistic label="待处理" :value="stats.pending" data-testid="stat-pending" /></n-card>
      </n-gi>
      <n-gi span="4 m:1">
        <n-card size="small"><n-statistic label="自动放行" :value="stats.autoAccepted" data-testid="stat-auto-accepted" /></n-card>
      </n-gi>
      <n-gi span="4 m:1">
        <n-card size="small"><n-statistic label="已授权命令" :value="stats.grantedCommands" data-testid="stat-granted-commands" /></n-card>
      </n-gi>
    </n-grid>

    <n-tabs v-model:value="activeTab" type="line" data-testid="tab-bar">
      <n-tab-pane name="audits" tab="审核流水">
        <n-card size="small" style="margin-bottom:16px;" data-testid="filter-bar">
          <n-space align="end" :wrap="true">
            <n-date-picker v-model:value="filters.timeRange" type="daterange" clearable placeholder="时间范围" size="small" data-testid="filter-time-range" />
            <n-select v-model:value="filters.sessionKind" :options="[{label:'全部',value:''},{label:'chat',value:'chat'},{label:'workspace',value:'workspace'}]" size="small" style="width:120px;" placeholder="会话类型" data-testid="filter-session-kind" />
            <n-input v-model:value="filters.host" size="small" placeholder="主机 ID" style="width:120px;" data-testid="filter-host" />
            <n-input v-model:value="filters.operator" size="small" placeholder="操作人" style="width:120px;" data-testid="filter-operator" />
            <n-select v-model:value="filters.decision" :options="[{label:'全部',value:''},{label:'已批准',value:'approved'},{label:'已拒绝',value:'rejected'},{label:'自动放行',value:'auto_accepted'},{label:'待审核',value:'pending'}]" size="small" style="width:120px;" placeholder="决策" data-testid="filter-decision" />
            <n-input v-model:value="filters.toolName" size="small" placeholder="工具名称" style="width:120px;" data-testid="filter-tool-name" />
            <n-button type="primary" size="small" @click="applyFilters" data-testid="apply-filters-btn">筛选</n-button>
            <n-button size="small" @click="resetFilters" data-testid="reset-filters-btn">重置</n-button>
          </n-space>
        </n-card>

        <n-data-table
          :columns="auditColumns"
          :data="audits"
          :loading="auditLoading"
          :row-key="(row) => row.id"
          :row-props="(row) => ({ style: 'cursor:pointer', onClick: () => openDrawer(row) })"
          :bordered="false"
          size="small"
          :pagination="{ page: auditPage, pageSize: auditPageSize, pageCount: auditTotalPages, onChange: (p) => { auditPage = p; fetchAudits(); } }"
          data-testid="audit-table"
        />
      </n-tab-pane>

      <n-tab-pane name="grants" tab="授权列表">
        <n-space align="end" style="margin-bottom:12px;">
          <n-input v-model:value="grantsHostId" size="small" placeholder="按主机筛选" style="width:200px;" data-testid="grants-host-filter" />
          <n-button size="small" @click="fetchGrants(grantsHostId)" data-testid="grants-refresh-btn">
            <template #icon><RefreshCcwIcon :size="14" /></template>
            刷新
          </n-button>
        </n-space>

        <n-data-table
          :columns="grantColumns"
          :data="grants"
          :loading="grantsLoading"
          :row-key="(row) => row.id"
          :bordered="false"
          size="small"
          data-testid="grants-table"
        />
      </n-tab-pane>
    </n-tabs>

    <n-drawer v-model:show="drawerVisible" :width="420" placement="right" data-testid="detail-drawer">
      <n-drawer-content title="审批详情" closable>
        <template v-if="drawerRecord">
          <n-descriptions :column="1" label-placement="left" bordered size="small">
            <n-descriptions-item label="审批 ID">{{ drawerRecord.id }}</n-descriptions-item>
            <n-descriptions-item label="时间">{{ formatTime(drawerRecord.createdAt) }}</n-descriptions-item>
            <n-descriptions-item label="会话类型">{{ drawerRecord.sessionKind || "-" }}</n-descriptions-item>
            <n-descriptions-item label="主机">{{ drawerRecord.host || "-" }}</n-descriptions-item>
            <n-descriptions-item label="操作人">{{ drawerRecord.operator || "-" }}</n-descriptions-item>
            <n-descriptions-item label="工具">{{ drawerRecord.toolName || "-" }}</n-descriptions-item>
            <n-descriptions-item label="决策">
              <n-tag :type="decisionTagType(drawerRecord.decision)" size="small">{{ decisionLabel(drawerRecord.decision) }}</n-tag>
            </n-descriptions-item>
            <n-descriptions-item label="命令"><n-code>{{ drawerRecord.command || "-" }}</n-code></n-descriptions-item>
            <n-descriptions-item label="备注">{{ drawerRecord.notes || "-" }}</n-descriptions-item>
          </n-descriptions>
        </template>
      </n-drawer-content>
    </n-drawer>
  </div>
</template>

<style scoped>
.approval-page {
  min-height: 100%;
  padding: 24px;
  display: flex;
  flex-direction: column;
  gap: 18px;
  background: linear-gradient(180deg, #f8fbff 0%, #f8fafc 100%);
}
.approval-header { display: flex; flex-direction: column; gap: 10px; }
.header-copy h1 { margin: 8px 0 4px; font-size: 28px; color: #0f172a; }
.header-copy p { margin: 0; color: #475569; line-height: 1.7; }
</style>

// web/src/pages/ApprovalManagementPage.tsx
import { Search } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ComplexPageFrame, EmptyPanel, KeyValueList, MetricStrip, RiskBadge } from "@/pages/complexPageComponents";
import {
  compactText,
  fetchApprovalAudits,
  fetchApprovalGrants,
  updateApprovalGrant,
  type ApprovalAuditRecord,
  type ApprovalGrantRecord,
} from "@/pages/complexPagesApi";
import { LoadingState, SelectField, StatusAlert } from "@/pages/settingsComponents";

function decisionLabel(decision?: string) {
  switch (decision) {
    case "approved":
      return "已批准";
    case "rejected":
      return "已拒绝";
    case "auto_accepted":
      return "自动放行";
    case "pending":
      return "待审核";
    default:
      return decision || "未知";
  }
}

function formatTime(value?: string) {
  if (!value) return "-";
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? value : date.toLocaleString("zh-CN", { hour12: false });
}

export function ApprovalManagementPage() {
  const [activeTab, setActiveTab] = useState("audits");
  const [audits, setAudits] = useState<ApprovalAuditRecord[]>([]);
  const [grants, setGrants] = useState<ApprovalGrantRecord[]>([]);
  const [stats, setStats] = useState<Record<string, unknown>>({});
  const [decision, setDecision] = useState("");
  const [host, setHost] = useState("");
  const [selectedAudit, setSelectedAudit] = useState<ApprovalAuditRecord | null>(null);
  const [loading, setLoading] = useState(true);
  const [message, setMessage] = useState<{ type: "success" | "error" | "info"; text: string } | null>(null);

  const filteredAudits = useMemo(() => {
    return audits.filter((item) => (!decision || item.decision === decision) && (!host || compactText(item.host).includes(host)));
  }, [audits, decision, host]);

  async function loadAudits() {
    setLoading(true);
    try {
      const payload = await fetchApprovalAudits({ page: "1", pageSize: "50", decision, host });
      setAudits(payload.items || payload.audits || []);
      setStats(payload.stats || {});
      setMessage(null);
    } catch (error) {
      setMessage({ type: "error", text: error instanceof Error ? error.message : "加载审批流水失败" });
    } finally {
      setLoading(false);
    }
  }

  async function loadGrants(nextHost = host) {
    setLoading(true);
    try {
      const payload = await fetchApprovalGrants(nextHost);
      setGrants(payload.items || payload.grants || []);
      setMessage(null);
    } catch (error) {
      setMessage({ type: "error", text: error instanceof Error ? error.message : "加载授权记录失败" });
    } finally {
      setLoading(false);
    }
  }

  async function grantAction(grantId: string, action: "revoke" | "disable" | "enable") {
    try {
      await updateApprovalGrant(grantId, action);
      await loadGrants(host);
      setMessage({ type: "success", text: "授权状态已更新" });
    } catch (error) {
      setMessage({ type: "error", text: error instanceof Error ? error.message : "更新授权失败" });
    }
  }

  useEffect(() => {
    void loadAudits();
  }, []);

  return (
    <ComplexPageFrame
      kicker="Approvals"
      title="审批管理"
      description="集中查看审批流水、授权记录，管理命令授权的生命周期。"
    >
      {message ? <StatusAlert type={message.type} title={message.type === "error" ? "操作失败" : "操作完成"} message={message.text} /> : null}
      <div data-testid="stats-row">
        <MetricStrip
          items={[
            { label: "今日审批", value: String(stats.todayTotal ?? audits.length) },
            { label: "待审核", value: String(stats.pending ?? audits.filter((item) => item.decision === "pending").length), tone: "warn" },
            { label: "自动放行", value: String(stats.autoAccepted ?? audits.filter((item) => item.decision === "auto_accepted").length), tone: "ok" },
            { label: "授权命令", value: String(stats.grantedCommands ?? grants.length) },
          ]}
        />
      </div>
      <Tabs value={activeTab} onValueChange={(value) => { setActiveTab(value); if (value === "grants") void loadGrants(host); }}>
        <TabsList>
          <TabsTrigger value="audits">审批流水</TabsTrigger>
          <TabsTrigger value="grants">授权记录</TabsTrigger>
        </TabsList>
        <TabsContent value="audits">
          <Card className="rounded-lg bg-white">
            <CardHeader>
              <CardTitle>审批流水</CardTitle>
              <CardDescription>兼容 `/approval-audits` 的 items/audits 返回结构。</CardDescription>
            </CardHeader>
            <CardContent className="grid gap-3">
              <div className="grid gap-2 md:grid-cols-[1fr_180px_180px_120px]" data-testid="filter-bar">
                <label className="relative" data-testid="filter-host">
                  <Search className="pointer-events-none absolute left-2.5 top-2 h-4 w-4 text-slate-400" />
                  <Input className="pl-8" value={host} onChange={(event) => setHost(event.target.value)} placeholder="按主机过滤" />
                </label>
                <SelectField value={decision} onChange={setDecision} options={[{ label: "全部决策", value: "" }, { label: "pending", value: "pending" }, { label: "approved", value: "approved" }, { label: "rejected", value: "rejected" }, { label: "auto_accepted", value: "auto_accepted" }]} />
                <Button variant="outline" onClick={() => void loadAudits()} data-testid="apply-filters-btn">应用过滤</Button>
                <Button variant="ghost" onClick={() => { setHost(""); setDecision(""); }} data-testid="reset-filters-btn">重置</Button>
              </div>
              {loading ? <LoadingState label="加载审批流水" /> : filteredAudits.length ? (
                <div className="overflow-x-auto">
                  <table className="w-full min-w-[860px] text-left text-sm" data-testid="audit-table">
                    <thead className="border-b text-xs uppercase tracking-normal text-slate-500">
                      <tr><th className="py-2 pr-3">时间</th><th className="py-2 pr-3">主机</th><th className="py-2 pr-3">工具</th><th className="py-2 pr-3">决策</th><th className="py-2 text-right">操作</th></tr>
                    </thead>
                    <tbody className="divide-y">
                      {filteredAudits.map((item) => (
                        <tr key={item.id} className="cursor-pointer hover:bg-slate-50" onClick={() => setSelectedAudit(item)}>
                          <td className="py-3 pr-3">{formatTime(item.createdAt)}</td>
                          <td className="py-3 pr-3">{item.host || "-"}</td>
                          <td className="py-3 pr-3">{item.toolName || item.command || "-"}</td>
                          <td className="py-3 pr-3"><RiskBadge value={decisionLabel(item.decision)} /></td>
                          <td className="py-3 text-right"><Button variant="outline" onClick={(event) => { event.stopPropagation(); setSelectedAudit(item); }}>详情</Button></td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              ) : <EmptyPanel title="暂无审批流水" description="调整过滤条件或稍后再试。" />}
            </CardContent>
          </Card>
        </TabsContent>
        <TabsContent value="grants">
          <Card className="rounded-lg bg-white">
            <CardHeader><CardTitle>授权记录</CardTitle><CardDescription>支持 revoke/disable/enable 生命周期操作。</CardDescription></CardHeader>
            <CardContent className="grid gap-3">
              {loading ? <LoadingState label="加载授权记录" /> : grants.length ? (
                <div className="overflow-x-auto">
                  <table className="w-full min-w-[760px] text-left text-sm" data-testid="grants-table">
                    <thead className="border-b text-xs uppercase tracking-normal text-slate-500"><tr><th className="py-2 pr-3">授权 ID</th><th className="py-2 pr-3">主机</th><th className="py-2 pr-3">命令/工具</th><th className="py-2 pr-3">状态</th><th className="py-2 text-right">操作</th></tr></thead>
                    <tbody className="divide-y">
                      {grants.map((grant) => (
                        <tr key={grant.id}>
                          <td className="py-3 pr-3">{grant.id}</td><td className="py-3 pr-3">{grant.hostId || "-"}</td><td className="py-3 pr-3">{grant.command || grant.toolName || "-"}</td><td className="py-3 pr-3"><RiskBadge value={grant.status} /></td>
                          <td className="py-3"><div className="flex justify-end gap-2">{grant.status === "disabled" ? <Button variant="outline" onClick={() => void grantAction(grant.id, "enable")}>启用</Button> : <><Button variant="outline" onClick={() => void grantAction(grant.id, "disable")}>禁用</Button><Button variant="destructive" onClick={() => void grantAction(grant.id, "revoke")}>撤销</Button></>}</div></td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              ) : <EmptyPanel title="暂无授权记录" description="没有符合条件的授权。" />}
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>

      <Sheet open={Boolean(selectedAudit)} onOpenChange={(open) => !open && setSelectedAudit(null)}>
        <SheetContent className="sm:max-w-lg" data-testid="detail-drawer">
          <SheetHeader><SheetTitle>审批详情</SheetTitle><SheetDescription>{selectedAudit?.id}</SheetDescription></SheetHeader>
          <div className="px-4">
            <KeyValueList items={[
              { label: "时间", value: formatTime(selectedAudit?.createdAt) },
              { label: "主机", value: selectedAudit?.host },
              { label: "操作人", value: selectedAudit?.operator },
              { label: "工具", value: selectedAudit?.toolName },
              { label: "决策", value: decisionLabel(selectedAudit?.decision) },
              { label: "原因", value: selectedAudit?.reason },
            ]} />
          </div>
        </SheetContent>
      </Sheet>
    </ComplexPageFrame>
  );
}
