// web/src/pages/ERPHealthPage.tsx
import { useEffect, useState } from "react";
import { Link } from "react-router-dom";

import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { SettingsPageFrame, ToneBadge } from "@/pages/settingsComponents";
import "./erpSrePages.css";

type Capability = { id?: string; name?: string; status?: string; summary?: string };
type Metric = { id?: string; name?: string; value?: string; trend?: number[] };
type Tenant = { id?: string; name?: string; impact?: string; severity?: string };

async function requestJson<T>(path: string, init: RequestInit = {}): Promise<T> {
  const response = await fetch(new URL(path, window.location.origin).toString(), { credentials: "include", ...init, headers: { "Content-Type": "application/json", ...(init.headers || {}) } });
  const payload = (await response.json().catch(() => ({}))) as T;
  if (!response.ok) throw new Error(`Request failed: ${response.status}`);
  return payload;
}

export function ERPHealthPage() {
  const [capabilities, setCapabilities] = useState<Capability[]>([]);
  const [metrics, setMetrics] = useState<Metric[]>([]);
  const [tenants, setTenants] = useState<Tenant[]>([]);

  useEffect(() => {
    async function load() {
      const [health, metricPayload, tenantPayload] = await Promise.all([
        requestJson<{ capabilities?: Capability[] }>("/api/v1/erp/health?environment=prod"),
        requestJson<{ metrics?: Metric[]; items?: Metric[] }>("/api/v1/erp/business-metrics"),
        requestJson<{ tenants?: Tenant[]; items?: Tenant[] }>("/api/v1/erp/tenant-impact"),
      ]);
      setCapabilities(health.capabilities || []);
      setMetrics(metricPayload.metrics || metricPayload.items || []);
      setTenants(tenantPayload.tenants || tenantPayload.items || []);
    }
    void load().catch(() => undefined);
  }, []);

  async function createIncidentFromHealth() {
    const degraded = capabilities.find((item) => item.status && item.status !== "healthy");
    await requestJson("/api/v1/incidents", {
      method: "POST",
      body: JSON.stringify({
        source: "erp-health",
        title: "ERP 健康异常",
        severity: "SEV2",
        environment: "prod",
        businessCapability: degraded?.name || "ERP",
      }),
    }).catch(() => undefined);
  }

  return (
    <section className="erp-sre-page">
      <div className="erp-sre-shell">
        <SettingsPageFrame
          title="ERP 健康"
          description="按业务能力、关键指标和租户影响查看 ERP 生产状态。"
          actions={
            <>
              <Button data-testid="erp-create-incident" onClick={() => void createIncidentFromHealth()}>创建事故</Button>
              <Button asChild variant="outline"><Link to="/incidents">事故工作台</Link></Button>
              <Button asChild variant="outline"><Link to="/opsgraph">ERP 图谱</Link></Button>
              <Button asChild variant="outline"><Link to="/coroot">Coroot 高级详情</Link></Button>
            </>
          }
        >
          <Card className="erp-sre-panel rounded-lg bg-white">
            <CardHeader><CardTitle>业务能力健康矩阵</CardTitle></CardHeader>
            <CardContent className="grid gap-2 md:grid-cols-2 xl:grid-cols-3">
              {capabilities.map((item) => (
                <article key={item.id || item.name} className="rounded-lg border bg-slate-50 p-3">
                  <div className="font-medium text-slate-900">{item.name || item.id}</div>
                  <div className="mt-2"><ToneBadge tone={item.status === "healthy" ? "success" : "warning"}>{item.status || "unknown"}</ToneBadge></div>
                  <p className="mt-2 text-sm text-slate-600">{item.summary || "暂无摘要"}</p>
                </article>
              ))}
            </CardContent>
          </Card>

          <section className="erp-sre-grid two grid gap-4 lg:grid-cols-2">
            <Card className="erp-sre-panel rounded-lg bg-white">
              <CardHeader><CardTitle>关键业务指标</CardTitle></CardHeader>
              <CardContent className="grid gap-2">
                {metrics.map((metric) => (
                  <div key={metric.id || metric.name} className="rounded-lg border p-3">
                    <div className="font-medium">{metric.name}</div>
                    <div className="text-lg font-semibold">{metric.value}</div>
                    <div className="mt-2 flex h-8 items-end gap-1">{(metric.trend || []).map((value, index) => <span key={index} className="w-4 rounded bg-slate-300" style={{ height: `${Math.max(10, Math.min(100, value))}%` }} />)}</div>
                  </div>
                ))}
              </CardContent>
            </Card>
            <Card className="erp-sre-panel rounded-lg bg-white">
              <CardHeader><CardTitle>受影响租户</CardTitle></CardHeader>
              <CardContent className="grid gap-2">
                {tenants.map((tenant) => (
                  <div key={tenant.id || tenant.name} className="rounded-lg border p-3">
                    <div className="font-medium">{tenant.name || tenant.id}</div>
                    <p className="text-sm text-slate-600">{tenant.impact}</p>
                  </div>
                ))}
              </CardContent>
            </Card>
          </section>
        </SettingsPageFrame>
      </div>
    </section>
  );
}

// web/src/pages/ERPHealthPage.vue
<script setup>
import { computed, onMounted } from "vue";
import { useAppStore } from "../store";
import BusinessMetricSparkline from "../components/erp/BusinessMetricSparkline.vue";
import ERPHealthMatrix from "../components/erp/ERPHealthMatrix.vue";
import TenantImpactList from "../components/erp/TenantImpactList.vue";
import "./erpSrePages.css";

const store = useAppStore();
const capabilities = computed(() => Array.isArray(store.erp.health?.capabilities) ? store.erp.health.capabilities : []);
const metrics = computed(() => Array.isArray(store.erp.businessMetrics) ? store.erp.businessMetrics : []);
const tenants = computed(() => Array.isArray(store.erp.tenantImpact) ? store.erp.tenantImpact : []);

async function loadERPHealthContext() {
  await Promise.allSettled([
    store.loadERPHealth(),
    store.loadERPBusinessMetrics(),
    store.loadERPTenantImpact(),
  ]);
}

async function createIncidentFromHealth() {
  await store.createIncident({
    source: "erp-health",
    title: "ERP 健康异常",
    severity: "SEV2",
    environment: "prod",
    businessCapability: capabilities.value.find((item) => item.status && item.status !== "healthy")?.name || "ERP",
  });
}

onMounted(() => {
  void loadERPHealthContext();
});
</script>

<template>
  <section class="erp-sre-page">
    <div class="erp-sre-shell">
      <header class="erp-sre-heading">
        <div>
          <p class="erp-sre-kicker">ERP Health</p>
          <h2>ERP 健康</h2>
          <p>按业务能力、关键指标和租户影响查看 ERP 生产状态。</p>
        </div>
        <div class="erp-sre-actions">
          <button class="erp-sre-link" type="button" data-testid="erp-create-incident" @click="createIncidentFromHealth">创建事故</button>
          <RouterLink class="erp-sre-link-secondary" to="/incidents">事故工作台</RouterLink>
          <RouterLink class="erp-sre-link-secondary" to="/opsgraph">ERP 图谱</RouterLink>
          <RouterLink class="erp-sre-link-secondary" to="/coroot">Coroot 高级详情</RouterLink>
        </div>
      </header>

      <section class="erp-sre-panel">
        <h3>业务能力健康矩阵</h3>
        <ERPHealthMatrix :capabilities="capabilities" />
      </section>

      <section class="erp-sre-grid two">
        <article class="erp-sre-panel">
          <h3>关键业务指标</h3>
          <div class="erp-sre-stack">
            <BusinessMetricSparkline v-for="metric in metrics" :key="metric.id || metric.name" :metric="metric" />
            <p v-if="!metrics.length">暂无关键指标</p>
          </div>
        </article>
        <article class="erp-sre-panel">
          <h3>受影响租户</h3>
          <TenantImpactList :tenants="tenants" />
        </article>
      </section>
    </div>
  </section>
</template>

<style scoped>
.erp-sre-stack {
  display: flex;
  flex-direction: column;
  gap: 10px;
}
</style>
