// web/src/pages/OpsGraphPage.tsx
import { useState } from "react";
import { Link } from "react-router-dom";

import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { SettingsPageFrame, ToneBadge } from "@/pages/settingsComponents";
import "./erpSrePages.css";

type Entity = { id?: string; name?: string; type?: string; status?: string; relation?: string; impact?: string };

async function requestJson<T>(path: string, init: RequestInit = {}): Promise<T> {
  const response = await fetch(new URL(path, window.location.origin).toString(), { credentials: "include", ...init, headers: { "Content-Type": "application/json", ...(init.headers || {}) } });
  const payload = (await response.json().catch(() => ({}))) as T;
  if (!response.ok) throw new Error(`Request failed: ${response.status}`);
  return payload;
}

export function OpsGraphPage() {
  const [query, setQuery] = useState("");
  const [lookupRows, setLookupRows] = useState<Entity[]>([]);
  const [selectedEntity, setSelectedEntity] = useState<Entity>({});
  const [neighbors, setNeighbors] = useState<Entity[]>([]);
  const [impact, setImpact] = useState<{ capabilities?: Entity[]; tenants?: Entity[] }>({});

  async function searchEntity() {
    const text = query.trim();
    if (!text) return;
    const lookup = await requestJson<{ matches?: Entity[]; items?: Entity[] }>("/api/v1/opsgraph/lookup", { method: "POST", body: JSON.stringify({ query: text }) }).catch(() => ({ matches: [{ id: text, name: text, type: "service" }] }));
    const matches = lookup.matches || lookup.items || [];
    const entity = matches[0] || { id: text, name: text };
    const entityId = entity.id || entity.name || text;
    const [neighborhood, businessImpact] = await Promise.all([
      requestJson<{ entity?: Entity; neighbors?: Entity[] }>(`/api/v1/opsgraph/entities/${encodeURIComponent(entityId)}/neighborhood?depth=2`).catch(() => ({ entity, neighbors: [] })),
      requestJson<{ capabilities?: Entity[]; tenants?: Entity[] }>(`/api/v1/opsgraph/entities/${encodeURIComponent(entityId)}/business-impact`).catch(() => ({ capabilities: [], tenants: [] })),
    ]);
    setLookupRows(matches);
    setSelectedEntity(neighborhood.entity || entity);
    setNeighbors(neighborhood.neighbors || []);
    setImpact(businessImpact);
  }

  return (
    <section className="erp-sre-page">
      <div className="erp-sre-shell">
        <SettingsPageFrame
          title="ERP 图谱"
          description="以实体搜索、邻域和业务影响为主，不做复杂全屏图谱。"
          actions={<><Button asChild variant="outline"><Link to="/erp">ERP 健康</Link></Button><Button asChild><Link to="/incidents">事故工作台</Link></Button></>}
        >
          <Card className="erp-sre-panel rounded-lg bg-white">
            <CardHeader><CardTitle>实体搜索</CardTitle></CardHeader>
            <CardContent>
              <div className="opsgraph-search flex gap-2">
                <input className="min-h-9 flex-1 rounded-lg border px-3" value={query} onChange={(event) => setQuery(event.target.value)} data-testid="opsgraph-search-input" placeholder="service / tenant / db / job" />
                <button className="rounded-lg border border-emerald-700 bg-emerald-50 px-4 font-semibold text-emerald-900" type="button" data-testid="opsgraph-search-button" onClick={() => void searchEntity()}>搜索</button>
              </div>
              <div className="opsgraph-lookup mt-3 flex flex-wrap gap-2">{lookupRows.map((item) => <span key={item.id || item.name} className="rounded-full bg-slate-100 px-2 py-1 text-xs">{item.name || item.id}</span>)}</div>
            </CardContent>
          </Card>

          <section className="erp-sre-layout grid gap-4 xl:grid-cols-[minmax(0,1fr)_420px]">
            <Card className="erp-sre-panel rounded-lg bg-white">
              <CardHeader><CardTitle>邻域概览</CardTitle></CardHeader>
              <CardContent className="grid gap-3">
                <article className="rounded-lg border bg-slate-50 p-4">
                  <div className="text-lg font-semibold">{selectedEntity.name || selectedEntity.id || "未选择实体"}</div>
                  <div className="mt-2 flex gap-2"><ToneBadge>{selectedEntity.type || "entity"}</ToneBadge><ToneBadge>{selectedEntity.status || "unknown"}</ToneBadge></div>
                </article>
                <div className="grid gap-2 md:grid-cols-2">
                  {neighbors.map((neighbor) => <div key={neighbor.id || neighbor.name} className="rounded-lg border p-3">{neighbor.name || neighbor.id}<div className="text-xs text-slate-500">{neighbor.relation}</div></div>)}
                </div>
              </CardContent>
            </Card>
            <aside className="erp-sre-grid grid gap-4">
              <Card className="erp-sre-panel rounded-lg bg-white"><CardHeader><CardTitle>邻域列表</CardTitle></CardHeader><CardContent className="grid gap-2">{neighbors.map((neighbor) => <div key={neighbor.id || neighbor.name}>{neighbor.name || neighbor.id}</div>)}</CardContent></Card>
              <Card className="erp-sre-panel rounded-lg bg-white"><CardHeader><CardTitle>业务影响</CardTitle></CardHeader><CardContent className="grid gap-3"><div>{(impact.capabilities || []).map((item) => <p key={item.name || item.id}>{item.name || item.id}: {item.impact}</p>)}</div><div>{(impact.tenants || []).map((item) => <p key={item.name || item.id}>{item.name || item.id}: {item.impact}</p>)}</div></CardContent></Card>
            </aside>
          </section>
        </SettingsPageFrame>
      </div>
    </section>
  );
}

// web/src/pages/OpsGraphPage.vue
<script setup>
import { computed, ref } from "vue";
import { useAppStore } from "../store";
import BusinessImpactPanel from "../components/opsgraph/BusinessImpactPanel.vue";
import OpsGraphEntityCard from "../components/opsgraph/OpsGraphEntityCard.vue";
import OpsGraphMiniMap from "../components/opsgraph/OpsGraphMiniMap.vue";
import OpsGraphNeighborList from "../components/opsgraph/OpsGraphNeighborList.vue";
import "./erpSrePages.css";

const store = useAppStore();
const query = ref("");
const selectedEntity = computed(() =>
  store.opsgraph.neighborhood?.entity ||
  (Array.isArray(store.opsgraph.lookup) ? store.opsgraph.lookup[0] : null) ||
  {},
);
const lookupRows = computed(() => Array.isArray(store.opsgraph.lookup) ? store.opsgraph.lookup : []);
const neighbors = computed(() => Array.isArray(store.opsgraph.neighborhood?.neighbors) ? store.opsgraph.neighborhood.neighbors : []);
const businessImpact = computed(() => store.opsgraph.businessImpact || {});

async function searchEntity() {
  const text = query.value.trim();
  if (!text) return;
  const result = await store.lookupOpsGraph({ query: text });
  const entity = result?.matches?.[0] || store.opsgraph.lookup?.[0] || selectedEntity.value;
  const entityId = entity?.id || entity?.name || text;
  await Promise.allSettled([
    store.loadOpsGraphNeighborhood(entityId),
    store.loadOpsGraphBusinessImpact(entityId),
  ]);
}
</script>

<template>
  <section class="erp-sre-page">
    <div class="erp-sre-shell">
      <header class="erp-sre-heading">
        <div>
          <p class="erp-sre-kicker">Ops Graph</p>
          <h2>ERP 图谱</h2>
          <p>以实体搜索、邻域和业务影响为主，不做复杂全屏图谱。</p>
        </div>
        <div class="erp-sre-actions">
          <RouterLink class="erp-sre-link-secondary" to="/erp">ERP 健康</RouterLink>
          <RouterLink class="erp-sre-link" to="/incidents">事故工作台</RouterLink>
        </div>
      </header>

      <section class="erp-sre-panel">
        <h3>实体搜索</h3>
        <div class="opsgraph-search">
          <input v-model="query" data-testid="opsgraph-search-input" placeholder="service / tenant / db / job" />
          <button type="button" data-testid="opsgraph-search-button" @click="searchEntity">搜索</button>
        </div>
        <div class="opsgraph-lookup">
          <span v-for="item in lookupRows" :key="item.id || item.name">{{ item.name || item.id }}</span>
        </div>
      </section>

      <section class="erp-sre-layout">
        <main class="erp-sre-panel">
          <h3>邻域概览</h3>
          <OpsGraphEntityCard :entity="selectedEntity" />
          <OpsGraphMiniMap :entity="selectedEntity" :neighbors="neighbors" />
        </main>
        <aside class="erp-sre-grid">
          <article class="erp-sre-panel">
            <h3>邻域列表</h3>
            <OpsGraphNeighborList :neighbors="neighbors" />
          </article>
          <article class="erp-sre-panel">
            <h3>业务影响</h3>
            <BusinessImpactPanel :impact="businessImpact" />
          </article>
        </aside>
      </section>
    </div>
  </section>
</template>

<style scoped>
.opsgraph-search {
  display: flex;
  gap: 8px;
}

.opsgraph-search input {
  flex: 1;
  min-width: 0;
  min-height: 36px;
  padding: 0 10px;
  border: 1px solid #cbd5e1;
  border-radius: 8px;
}

.opsgraph-search button {
  min-height: 36px;
  padding: 0 14px;
  border: 1px solid #15803d;
  border-radius: 8px;
  background: #dcfce7;
  color: #14532d;
  font-weight: 800;
}

.opsgraph-lookup {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
  margin-top: 10px;
}

.opsgraph-lookup span {
  padding: 4px 8px;
  border-radius: 999px;
  background: #f1f5f9;
  color: #475569;
  font-size: 12px;
}
</style>
